name: form-submit-overlay-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/form-submit-overlay/__tests__/**/*.test.js'
      - 'packages/form-submit-overlay/src/**/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/form-submit-overlay/__tests__/**/*.test.js'
      - 'packages/form-submit-overlay/src/**/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run lint -w '@w0s/form-submit-overlay'
