name: input-date-to-text-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'customelements/input-date-to-text/__tests__/*.test.js'
      - 'customelements/input-date-to-text/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'customelements/input-date-to-text/__tests__/*.test.js'
      - 'customelements/input-date-to-text/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test -w '@saekitominaga/customelements-input-date-totext'

      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
