name: report-js-error-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/js-error/__tests__/**/*.test.js'
      - 'packages/js-error/src/**/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/js-error/__tests__/**/*.test.js'
      - 'packages/js-error/src/**/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test -w '@w0s/report-js-error'
