name: report-same-referrer-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/same-referrer/__tests__/*.test.js'
      - 'packages/same-referrer/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/same-referrer/__tests__/*.test.js'
      - 'packages/same-referrer/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test -w '@w0s/report-same-referrer'
