name: report-same-referrer-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'report/same-referrer/__tests__/*.test.js'
      - 'report/same-referrer/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'report/same-referrer/__tests__/*.test.js'
      - 'report/same-referrer/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test -w '@saekitominaga/report-same-referrer'

      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
