name: Running the `input-file-preview` test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/input-file-preview/__tests__/**/*.test.js'
      - 'packages/input-file-preview/src/**/*.ts'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test -w '@w0s/input-file-preview'
