name: textarea-auto-size-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'javascript/textarea-auto-size/__tests__/*.test.js'
      - 'javascript/textarea-auto-size/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'javascript/textarea-auto-size/__tests__/*.test.js'
      - 'javascript/textarea-auto-size/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint -w '@saekitominaga/customelements-textarea-autoheight'
